// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    credits
    (
        init => init
        upgrade => upgrade
        addCredits => add_credits
        getCredits => get_credits
        isPaused => get_is_paused
        getCreditsPerEgld => get_credits_per_egld
        changeNumCreditsPerEGLD => change_num_credits_per_egld
        pause => pause
        unpause => unpause
        withdrawAll => withdraw_all
        migrate => migrate
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
